//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AASD_Data_Access_Layer.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class AASD_DB_Query
    {
        public AASD_DB_Query()
        {
            this.AASD_DB_Result = new HashSet<AASD_DB_Result>();
        }
    
        public System.Guid Query_Id { get; set; }
        public string Search_string { get; set; }
        public string Context { get; set; }
        public System.DateTime Creation_Time { get; set; }
    
        public virtual ICollection<AASD_DB_Result> AASD_DB_Result { get; set; }
    }
}
