<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:tns="http://schemas.thinktecture.com/contractfirst/2009/07/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:msg="http://schemas.thinktecture.com/contractfirst/2009/07/"
                  xmlns:ns="http://schemas.thinktecture.com/contractfirst/2009/07/data"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  targetNamespace="http://schemas.thinktecture.com/contractfirst/2009/07/">
  <wsdl:types>
    <xs:schema targetNamespace="
http://schemas.thinktecture.com/contractfirst/2009/07/"
               elementFormDefault="qualified">
      <xs:import schemaLocation="messages.xsd"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="exploreRequestMessage">
    <wsdl:part name="parameters" element="msg:explore"/>
  </wsdl:message>
  <wsdl:message name="exploreResponseMessage">
    <wsdl:part name="parameters" element="msg:exploreResponse"/>
  </wsdl:message>
  <wsdl:portType name="processExplorer">
    <wsdl:operation name="explore">
      <wsdl:input wsaw:Action="
http://schemas.thinktecture.com/contractfirst/2009/07/explore"
                  message="tns:exploreRequestMessage"/>
      <wsdl:output wsaw:Action="
http://schemas.thinktecture.com/contractfirst/2009/07/exploreResponse"
                   message="tns:exploreResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="processExplorerHttpBinding" type="tns:processExplorer">
    <soap12:binding style="document" transport="
http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="explore">
      <soap12:operation
        soapAction="http://schemas.thinktecture.com/contractfirst/2009/07/explore"
        soapActionRequired="true"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProcessExplorerService">
    <wsdl:port name="processExplorerPort" binding="tns:processExplorerHttpBinding">
      <soap12:address location="http://localhost/processexplorer"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>